apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: transmission
  labels:
    {{- include "transmission.labels" . | nindent 4 }}
spec:
  namespaceSelector:
    matchNames:
      - {{ .Release.Namespace }}
  selector:
    matchLabels:
      {{- include "transmission.selectorLabels" . | nindent 6 }}
  podMetricsEndpoints:
  - targetPort: 9190
