---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "transmission.fullname" . }}
  labels:
    {{- include "transmission.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "transmission.selectorLabels" . | nindent 4 }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "transmission.fullname" . }}-nat
  labels:
    {{- include "transmission.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.natPort }}
      targetPort: nat-port
      protocol: TCP
      name: nat-port
  selector:
    {{- include "transmission.selectorLabels" . | nindent 4 }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "transmission.fullname" . }}-nat-udp
  labels:
    {{- include "transmission.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.natPort }}
      targetPort: nat-port
      protocol: UDP
      name: nat-port
  selector:
    {{- include "transmission.selectorLabels" . | nindent 4 }}
